---
- name: httpd should be latest
  yum:
    name: httpd
    state: latest
  notify:
    - reload httpd

- name: httpd should be enabled on boot
  service:
    name: httpd
    enabled: yes

- name: create index.html file
  copy:
    content: <p>Welcome to my web server</p>
    dest: /var/www/html/index.html

- name: firewalld should be started and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: yes

- name: httpd should be permanently allowed via firewalld
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled
