---
- name: httpd should be latest
  yum:
    name: httpd
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: httpd should be started and enabled on boot
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: generate httpd.conf
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - reload httpd

- name: copy index.html file
  copy:
    src: files/index.html
    dest: /var/www/html/index.html
    owner: apache
    group: apache 

- name: firewalld should be started and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: yes

- name: httpd should be permanently allowed via firewalld
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled
