---
- name: First Playbook of Lesson1
  hosts: all
  become: yes
  tasks:
    - name: httpd should be latest
      yum:
        name: httpd
        state: latest

    - name: httpd should be started and enabled on boot
      service:
        name: httpd
        state: started
        enabled: yes

    - name: create index.html file
      copy:
        content: <p>Welcome to my web server</p>
        dest: /var/www/html/index.html

    - name: firewalld should be started and enabled on boot
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: httpd should be permanently allowed via firewalld
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled
