---
- name: Third Playbook of Lesson1
  hosts: all
  become: yes
  tasks:
    - name: Check presence of 'net.ifnames' parameter
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=.*net\.ifnames'
        state: absent
      check_mode: true
      changed_when: false
      register: grub_ifnames_check
    - name: Check presence of 'biosdevname' parameter
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=.*biosdevname'
        state: absent
      check_mode: true
      changed_when: false
      register: grub_biosdevname_check
    - name: Modify existing 'net.ifnames' parameter
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=(.*)net\.ifnames=\d+(.*)$'
        line: 'GRUB_CMDLINE_LINUX=\1net.ifnames=0\2'
        backrefs: yes
        validate: /bin/bash -n %s
      when: grub_ifnames_check.found == 1
    - name: Modify existing 'biosdevname' parameter
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=(.*)biosdevname=\d+(.*)$'
        line: 'GRUB_CMDLINE_LINUX=\1biosdevname=0\2'
        backrefs: yes
        validate: /bin/bash -n %s
      when: grub_biosdevname_check.found == 1
